language: go

go:
  - "1.12.4"

os:
  - linux
  - osx

sudo: false

branches:
  only:
  - master

services:
  - mongodb
  - redis-server


install: true

script:
  - go get -v -u github.com/valyala/fasthttp
  - go get -v -u github.com/valyala/gozstd
  - go get -v -u github.com/sirupsen/logrus
  - go get -v -u github.com/onrik/logrus/filename
  - go get -v -u github.com/go-redis/redis
  - go get -v -u github.com/globalsign/mgo
  - go get -v -u github.com/globalsign/mgo/bson
  - go get -v -u github.com/alessiosavi/GoUtils
  
  - pwd
  - ls
  - go build
  - redis-cli ping
  - ./Authentigo > log.out &
  - curl -L -k -s -v 'http://localhost:11001/auth/login?user=alessio12345&pass=test12345'
  - curl -L -k -s -v 'http://localhost:11001/auth/register?user=alessio12354&pass=test12345'
  - curl -L -k -s -v 'http://localhost:11001/auth/login?user=alessio12345&pass=test12345'
  - cat nolog.out