language: go

go:
  - "1.13.4"

os:
  - linux
  - osx

sudo: false

branches:
  only:
  - master

services:
  - mongodb
  - redis-server

script:
  - go clean
  - pwd
  - ls
  - redis-cli ping
  - go build
  - ./AuthentiGo 2&>1&> log.out &
  - go test -v test/authentigo_test.go
  - go test -v ./auth
  - pkill AuthentiGo
  - cat log.out