version: '3.3'
services:

  authentigo:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:11001:11001" 
    restart: always
    expose:
      - 11001
    depends_on: 
      - redisdb
      - mongodb
    network_mode: "host"
    volumes:
      - go-modules:/go/pkg/mod

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      - MONGO_DATA_DIR=/var/lib/mongo
    volumes:
      - mongo-db:/var/lib/mongo
    ports:
      - "0.0.0.0:27017:27017"
    expose: 
      - "27017"
    command: mongod
    network_mode: "host"


  redisdb:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "0.0.0.0:6379:6379"
    expose:
      - '6379'
    volumes:
      - redis-db:/var/lib/redis
    entrypoint: redis-server --appendonly yes
    network_mode: "host"
    
volumes:
  mongo-db:
  redis-db:
  go-modules:
