name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: golang:1.15.6-alpine
    steps:

    - name: Set up Go 1.15.6
      uses: actions/setup-go@v1
      with:
        go-version: 1.15.6
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go clean
        go mod download

    - name: Build
      run: go build -v .
    - name: Test
      run: go test ./auth
